---
boot:
  params:
    locales: fr_FR
  plugins:
    - io.vertigo.core.plugins.resource.classpath.ClassPathResourceResolverPlugin: {}
    - io.vertigo.vega.plugins.webservice.servlet.WebAppContextParamPlugin: {}
    - io.vertigo.core.plugins.param.xml.XmlParamPlugin:
        url : "/boot/config/application-config.xml" 
modules:
  io.vertigo.commons.CommonsFeatures:
    features:
      - script:
      - cache:
    featuresConfig:
      - script.janino:
      - cache.memory:
  io.vertigo.database.DatabaseFeatures:
    features:
      - sql:
    featuresConfig:
      - sql.c3p0:
          dataBaseClass: io.vertigo.database.impl.sql.vendor.h2.H2DataBase
          jdbcDriver: org.h2.Driver
          jdbcUrl: jdbc:h2:mem:database
  io.vertigo.dynamo.DynamoFeatures:
    features:
      - store:
      - kvStore:
    featuresConfig:
      - store.data.sql:
      - kvStore.delayedMemory:
          collections: flowers
          timeToLiveSeconds: 5
  io.vertigo.account.AccountFeatures:
    features:
      - security:
          userSessionClassName: io.vertigo.starterkit.user.VegaStartkitUserSession
  io.vertigo.vega.VegaFeatures:
    features:
        - webservices:
    featuresConfig:
        - webservices.token:
            tokens: vega-starterkit-tokens
        - webservices.rateLimiting:
        - webservices.security:
        - webservices.apiPrefix:
            apiPrefix: /api
  io.vertigo.starterkit.VegaStarterkitModuleDiscoveryFeatures:
