---
boot:
  params:
    locales: fr_FR
  plugins:
    - io.vertigo.core.plugins.resource.classpath.ClassPathResourceResolverPlugin: {}
    - io.vertigo.vega.plugins.webservice.servlet.WebAppContextParamPlugin: {}
modules:
  io.vertigo.commons.CommonsFeatures:
    features:
      - script:
      - cache:
    featuresConfig:
      - script.janino:
      - cache.memory:
      - analytics.socketLoggerConnector:
  io.vertigo.database.DatabaseFeatures:
    features:
      - sql:
    featuresConfig:
      - sql.datasource:
          classname: io.vertigo.database.impl.sql.vendor.postgresql.PostgreSqlDataBase
          source: java:/comp/env/jdbc/DataSource
  io.vertigo.dynamo.DynamoFeatures:
    features:
      - store:
      - kvStore:
      - domainMetrics:
    featuresConfig:
      - store.data.sql:
      - collections.luceneIndex:
      - kvStore.berkeley:
          collections: VViewContext;TTL=43200
          dbFilePath: ${java.io.tmpdir}/vertigo-ui/ViewContext
  io.vertigo.account.AccountFeatures:
    features:
      - security:
          userSessionClassName: ${package}.user.${projectName}UserSession
    featuresConfig:
  io.vertigo.vega.VegaFeatures:
    features:
        - webservices:
    featuresConfig:
        - webservices.rateLimiting:
        - webservices.security:
        - webservices.apiPrefix:
            apiPrefix: /api
  ${package}.${businessModuleLowerCase}.${businessModule}Features:
initializers:
  - ${package}.boot.I18nResourcesInitializer:
